apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: postgres-sample
spec:
  #
  # Global features
  #
  pgConfig:
    dbname: postgres-sample
    username: pgadmin
    appUser: pgappuser
    readOnlyUser: pgrouser
    readWriteUser: pgrwuser
  #  customConfig:
  #    postgresql:
  #      name:
  postgresVersion:
    name: postgres-15 # View available versions with `kubectl get postgresversion`
  serviceType: ClusterIP
  #  serviceAnnotations:
  readOnlyServiceType: ClusterIP
  #  readOnlyServiceAnnotations:
  seccompProfile:
    type: RuntimeDefault
  imagePullSecret:
    name: regsecret
  persistentVolumeClaimPolicy: delete
  #  highAvailability:
  #    enabled: true
  #    readReplicas: 1
  #  logLevel: Debug
  #  backupLocation:
  #    name: backuplocation-sample
  #  certificateSecretName:
  #  deploymentOptions:
  #    continuousRestoreTarget: true
  #    sourceStanzaName: <sample-stanza-from-prod-instance>

  #
  # Data Pod features
  #
  #  storageClassName:
  storageSize: 800M
  sharedMemorySize: 64Mi
  dataPodConfig:
    #    tolerations:
    #      - key:
    #        operator:
    #        value:
    #        effect:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - data
                      - monitor
                  - key: postgres-instance
                    operator: In
                    values:
                      - postgres-sample
              topologyKey: kubernetes.io/hostname
            weight: 100
  #
  # Monitor Pod features
  #
  #  monitorStorageClassName:
  monitorStorageSize: 1G
  monitorPodConfig:
    #    tolerations:
    #      - key:
    #        operator:
    #        value:
    #        effect:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - data
                      - monitor
                  - key: postgres-instance
                    operator: In
                    values:
                      - postgres-sample
              topologyKey: kubernetes.io/hostname
            weight: 100

  #
  # Resources
  #
  resources:
    data:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 800m
        memory: 800Mi
    monitor:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 800m
        memory: 800Mi
    metrics:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi