apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  retail-source-app
    app.kubernetes.io/name: retail-source-app
  name:  retail-source-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  retail-source-app
  template:
    metadata:
      labels:
        name:  retail-source-app
    spec:
      containers:
        - env:
            - name: server.port
              value: "8080"
            - name: spring.rabbitmq.host
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: host
            - name: spring.rabbitmq.username
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: spring.rabbitmq.password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
          image: cloudnativedata/retail-source-app:0.0.2-SNAPSHOT
          name: retail-source-app
          #          imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: retail-source-app-service
spec:
  selector:
    name:  retail-source-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
#  type: LoadBalancer