---
apiVersion: v1
kind: Service
metadata:
  name: gf-redis-locator-lb-service
spec:
  selector:
    app.kubernetes.io/component: gemfire-locator
  ports:
    - name: "locator"
      protocol: TCP
      port: 10334
      targetPort: 10334
    - name: "http"
      protocol: TCP
      port: 7070
      targetPort: 7070